import { SHA256_PATTERN } from "./model.js";
import type { RuntimeCounterSnapshot } from "./runtime-criteria.js";
import { REQUIRED_RUNTIME_SCENARIOS } from "./scenario-contract.js";
import type { RuntimeFixtureModel } from "./runtime-fixture-model.js";

export type GenericScenarioId = Exclude<(typeof REQUIRED_RUNTIME_SCENARIOS)[keyof typeof REQUIRED_RUNTIME_SCENARIOS]["id"], "decoder-throughput-300">;
export interface RawRuntimeCursor { readonly unit: string; readonly unitInstance: number; readonly localFrame: number; }
export type RawRuntimeGraphEffect =
  | Readonly<{ readonly type: "requestedstatechange"; readonly from: string; readonly to: string; readonly sequence: number }>
  | Readonly<{ readonly type: "transitionstart"; readonly edgeId: string; readonly from: string; readonly to: string; readonly sequence: number }>
  | Readonly<{ readonly type: "visualstatechange"; readonly from: string; readonly to: string }>
  | Readonly<{ readonly type: "transitionend"; readonly edgeId: string; readonly from: string; readonly to: string }>;
export interface RawRuntimeGraphEvent { readonly eventOrdinal: number; readonly traceIndex: number; readonly effect: RawRuntimeGraphEffect; }
export interface RawRuntimeScenarioFrame {
  readonly traceIndex: number; readonly presentationOrdinal: number; readonly rationalDeadlineMicroseconds: number; readonly eligibleAnimationFrameOrdinal: number;
  readonly callbackStartMicroseconds: number; readonly canvasSubmissionCompleteMicroseconds: number | null; readonly graphContentOrdinal: number | null;
  readonly graphRequestedState: string | null; readonly graphVisualState: string | null; readonly graphPendingEdge: string | null; readonly graphActiveEdge: string | null;
  readonly graphPresentationKind: "intro" | "body" | "locked" | "reversible" | null; readonly graphPresentationState: string | null; readonly graphPresentationEdge: string | null;
  readonly graphPresentationUnit: string | null; readonly graphPresentationFrame: number | null; readonly graphPresentationDirection: "forward" | "reverse" | null;
  readonly routeReady: boolean | null; readonly selectedBoundary: string | null; readonly mediaState: string | null; readonly mediaEdge: string | null; readonly mediaUnit: string | null;
  readonly mediaLocalFrame: number | null; readonly mediaUnitInstance: number | null; readonly mediaIntendedPresentationOrdinal: number | null; readonly submittedCursors: readonly RawRuntimeCursor[];
  readonly decodeLeadFrames: number | null; readonly cumulativeUnderflows: number;
}
export type RawRuntimeOperationEvent =
  | Readonly<{ readonly eventOrdinal: number; readonly atMicroseconds: number; readonly kind: "input"; readonly operationOrdinal: number; readonly inputSequence: number; readonly target: string }>
  | Readonly<{ readonly eventOrdinal: number; readonly atMicroseconds: number; readonly kind: "headed-dispatch"; readonly operationOrdinal: number; readonly eventType: "pointerenter" | "pointerleave" | "focusin" | "focusout" | "click" }>
  | Readonly<{ readonly eventOrdinal: number; readonly atMicroseconds: number; readonly kind: "promise"; readonly operationOrdinal: number; readonly status: "fulfilled" | "rejected"; readonly errorName: string | null }>
  | Readonly<{ readonly eventOrdinal: number; readonly atMicroseconds: number; readonly kind: "dom-event"; readonly name: "requestedstatechange" | "transitionstart" | "visualstatechange" | "transitionend"; readonly from: string; readonly to: string; readonly edge: string | null; readonly sequence: number | null }>;
export interface RawRuntimeResourceEvent { readonly eventOrdinal: number; readonly atMicroseconds: number; readonly kind: "acquired" | "retired"; readonly resourceId: string; readonly resourceBytes: number; readonly ownedResources: number; readonly ownedBytes: number; }
export interface RuntimeScenarioLedger {
  readonly schemaVersion: "1.0"; readonly ledgerKind: "runtime-scenario"; readonly candidateManifestDigest: string; readonly fixtureDigest: string; readonly scenarioId: GenericScenarioId;
  readonly repetition: number; readonly seed: number; readonly idealContentFrameIntervalMicroseconds: number; readonly frames: readonly RawRuntimeScenarioFrame[]; readonly operations: readonly RawRuntimeOperationEvent[];
  readonly graphEvents: readonly RawRuntimeGraphEvent[]; readonly terminalTrace: Readonly<{ readonly lastTraceIndex: number; readonly contentTickRecords: number; readonly cumulativeUnderflows: number }>;
  readonly counterBaseline: RuntimeCounterSnapshot; readonly counterTerminal: RuntimeCounterSnapshot; readonly resourceEvents: readonly RawRuntimeResourceEvent[];
  readonly cleanupReceipt: Readonly<{ readonly reason: "dispose"; readonly retiredResourceIds: readonly string[]; readonly ownedResources: number; readonly ownedBytes: number; readonly liveWorkers: number; readonly openFrames: number; readonly pendingLoads: number; readonly activeLeases: number; readonly stalePublications: number }>;
}
export interface RuntimeScenarioLedgerEvaluation { readonly passed: boolean; readonly boundaryCount: number; readonly frameCount: number; readonly operationCount: number; readonly headedOperationCount: number; readonly formatUnderflows: number; readonly firstFailingOrdinal: number | null; readonly thresholdMicroseconds: number; readonly failures: readonly string[]; }
export interface RuntimeScenarioLedgerExpectation { readonly candidateManifestDigest?: string; readonly fixtureDigest?: string; readonly fixture?: RuntimeFixtureModel; readonly scenarioId?: GenericScenarioId; readonly repetition?: number; readonly seed?: number; }

const ROOT_KEYS = ["schemaVersion", "ledgerKind", "candidateManifestDigest", "fixtureDigest", "scenarioId", "repetition", "seed", "idealContentFrameIntervalMicroseconds", "frames", "operations", "graphEvents", "counterBaseline", "counterTerminal", "resourceEvents", "cleanupReceipt", "terminalTrace"] as const;
const FRAME_KEYS = ["traceIndex", "presentationOrdinal", "rationalDeadlineMicroseconds", "eligibleAnimationFrameOrdinal", "callbackStartMicroseconds", "canvasSubmissionCompleteMicroseconds", "graphContentOrdinal", "graphRequestedState", "graphVisualState", "graphPendingEdge", "graphActiveEdge", "graphPresentationKind", "graphPresentationState", "graphPresentationEdge", "graphPresentationUnit", "graphPresentationFrame", "graphPresentationDirection", "routeReady", "selectedBoundary", "mediaState", "mediaEdge", "mediaUnit", "mediaLocalFrame", "mediaUnitInstance", "mediaIntendedPresentationOrdinal", "submittedCursors", "decodeLeadFrames", "cumulativeUnderflows"] as const;
const COUNTER_KEYS = ["configure", "reset", "flush", "reconfigure", "seek", "stalePublications", "capViolations", "untrackedOwnedBytes", "terminalOwnedResources"] as const;
const RECEIPT_KEYS = ["reason", "retiredResourceIds", "ownedResources", "ownedBytes", "liveWorkers", "openFrames", "pendingLoads", "activeLeases", "stalePublications"] as const;
const RESOURCE_KEYS = ["eventOrdinal", "atMicroseconds", "kind", "resourceId", "resourceBytes", "ownedResources", "ownedBytes"] as const;
const CURSOR_KEYS = ["unit", "unitInstance", "localFrame"] as const;
const SCENARIOS = new Set<GenericScenarioId>([REQUIRED_RUNTIME_SCENARIOS.loop.id, REQUIRED_RUNTIME_SCENARIOS.routes.id, REQUIRED_RUNTIME_SCENARIOS.inverse.id, REQUIRED_RUNTIME_SCENARIOS.portal.id, REQUIRED_RUNTIME_SCENARIOS.rapidInput.id, REQUIRED_RUNTIME_SCENARIOS.settlement.id]);

export function parseRuntimeScenarioLedger(input: unknown): RuntimeScenarioLedger {
  const root = exactRecord(input, ROOT_KEYS, "$scenario"); literal(root.schemaVersion, "1.0", "$scenario.schemaVersion"); literal(root.ledgerKind, "runtime-scenario", "$scenario.ledgerKind");
  const scenarioId = text(root.scenarioId, "$scenario.scenarioId") as GenericScenarioId; if (!SCENARIOS.has(scenarioId)) throw new TypeError("$scenario.scenarioId is invalid");
  return Object.freeze({
    schemaVersion: "1.0", ledgerKind: "runtime-scenario", candidateManifestDigest: digest(root.candidateManifestDigest, "$scenario.candidateManifestDigest"), fixtureDigest: digest(root.fixtureDigest, "$scenario.fixtureDigest"), scenarioId,
    repetition: boundedInteger(root.repetition, "$scenario.repetition", 1, 3), seed: nonnegativeInteger(root.seed, "$scenario.seed"), idealContentFrameIntervalMicroseconds: positiveInteger(root.idealContentFrameIntervalMicroseconds, "$scenario.idealContentFrameIntervalMicroseconds"),
    frames: Object.freeze(array(root.frames, "$scenario.frames", 2_000_000).map(parseFrame)), operations: Object.freeze(array(root.operations, "$scenario.operations", 100_000).map(parseOperation)), graphEvents: Object.freeze(array(root.graphEvents, "$scenario.graphEvents", 100_000).map(parseGraphEvent)),
    counterBaseline: parseCounters(root.counterBaseline, "$scenario.counterBaseline"), counterTerminal: parseCounters(root.counterTerminal, "$scenario.counterTerminal"), resourceEvents: Object.freeze(array(root.resourceEvents, "$scenario.resourceEvents", 100_000).map(parseResourceEvent)), cleanupReceipt: parseCleanupReceipt(root.cleanupReceipt), terminalTrace: parseTerminalTrace(root.terminalTrace)
  });
}

function parseFrame(value: unknown, index: number): RawRuntimeScenarioFrame {
  const path = `$scenario.frames[${String(index)}]`; const frame = exactRecord(value, FRAME_KEYS, path); const callbackStartMicroseconds = nonnegativeInteger(frame.callbackStartMicroseconds, `${path}.callbackStartMicroseconds`); const submission = nullableInteger(frame.canvasSubmissionCompleteMicroseconds, `${path}.canvasSubmissionCompleteMicroseconds`); if (submission !== null && submission < callbackStartMicroseconds) throw new RangeError(`${path} canvas submission precedes callback`);
  return Object.freeze({ traceIndex: nonnegativeInteger(frame.traceIndex, `${path}.traceIndex`), presentationOrdinal: positiveInteger(frame.presentationOrdinal, `${path}.presentationOrdinal`), rationalDeadlineMicroseconds: nonnegativeInteger(frame.rationalDeadlineMicroseconds, `${path}.rationalDeadlineMicroseconds`), eligibleAnimationFrameOrdinal: positiveInteger(frame.eligibleAnimationFrameOrdinal, `${path}.eligibleAnimationFrameOrdinal`), callbackStartMicroseconds, canvasSubmissionCompleteMicroseconds: submission,
    graphContentOrdinal: nullableInteger(frame.graphContentOrdinal, `${path}.graphContentOrdinal`), graphRequestedState: nullableText(frame.graphRequestedState, `${path}.graphRequestedState`), graphVisualState: nullableText(frame.graphVisualState, `${path}.graphVisualState`), graphPendingEdge: nullableText(frame.graphPendingEdge, `${path}.graphPendingEdge`), graphActiveEdge: nullableText(frame.graphActiveEdge, `${path}.graphActiveEdge`), graphPresentationKind: frame.graphPresentationKind === null ? null : enumeration(frame.graphPresentationKind, ["intro", "body", "locked", "reversible"] as const, `${path}.graphPresentationKind`), graphPresentationState: nullableText(frame.graphPresentationState, `${path}.graphPresentationState`), graphPresentationEdge: nullableText(frame.graphPresentationEdge, `${path}.graphPresentationEdge`), graphPresentationUnit: nullableText(frame.graphPresentationUnit, `${path}.graphPresentationUnit`), graphPresentationFrame: nullableInteger(frame.graphPresentationFrame, `${path}.graphPresentationFrame`), graphPresentationDirection: frame.graphPresentationDirection === null ? null : enumeration(frame.graphPresentationDirection, ["forward", "reverse"] as const, `${path}.graphPresentationDirection`), routeReady: nullableBoolean(frame.routeReady, `${path}.routeReady`), selectedBoundary: nullableText(frame.selectedBoundary, `${path}.selectedBoundary`), mediaState: nullableText(frame.mediaState, `${path}.mediaState`), mediaEdge: nullableText(frame.mediaEdge, `${path}.mediaEdge`), mediaUnit: nullableText(frame.mediaUnit, `${path}.mediaUnit`), mediaLocalFrame: nullableInteger(frame.mediaLocalFrame, `${path}.mediaLocalFrame`), mediaUnitInstance: nullableInteger(frame.mediaUnitInstance, `${path}.mediaUnitInstance`), mediaIntendedPresentationOrdinal: nullableInteger(frame.mediaIntendedPresentationOrdinal, `${path}.mediaIntendedPresentationOrdinal`), submittedCursors: Object.freeze(array(frame.submittedCursors, `${path}.submittedCursors`, 4_096).map((cursor, cursorIndex) => parseCursor(cursor, `${path}.submittedCursors[${String(cursorIndex)}]`))), decodeLeadFrames: nullableInteger(frame.decodeLeadFrames, `${path}.decodeLeadFrames`), cumulativeUnderflows: nonnegativeInteger(frame.cumulativeUnderflows, `${path}.cumulativeUnderflows`) });
}
function parseGraphEvent(value: unknown, index: number): RawRuntimeGraphEvent { const path = `$scenario.graphEvents[${String(index)}]`; const event = exactRecord(value, ["eventOrdinal", "traceIndex", "effect"], path); return Object.freeze({ eventOrdinal: nonnegativeInteger(event.eventOrdinal, `${path}.eventOrdinal`), traceIndex: nonnegativeInteger(event.traceIndex, `${path}.traceIndex`), effect: parseEffect(event.effect, `${path}.effect`) }); }
function parseEffect(value: unknown, path: string): RawRuntimeGraphEffect { const effect = record(value, path); const type = enumeration(effect.type, ["requestedstatechange", "transitionstart", "visualstatechange", "transitionend"] as const, `${path}.type`); if (type === "requestedstatechange") { const exact = exactRecord(effect, ["type", "from", "to", "sequence"], path); return Object.freeze({ type, from: text(exact.from, `${path}.from`), to: text(exact.to, `${path}.to`), sequence: nonnegativeInteger(exact.sequence, `${path}.sequence`) }); } if (type === "transitionstart") { const exact = exactRecord(effect, ["type", "edgeId", "from", "to", "sequence"], path); return Object.freeze({ type, edgeId: text(exact.edgeId, `${path}.edgeId`), from: text(exact.from, `${path}.from`), to: text(exact.to, `${path}.to`), sequence: nonnegativeInteger(exact.sequence, `${path}.sequence`) }); } if (type === "transitionend") { const exact = exactRecord(effect, ["type", "edgeId", "from", "to"], path); return Object.freeze({ type, edgeId: text(exact.edgeId, `${path}.edgeId`), from: text(exact.from, `${path}.from`), to: text(exact.to, `${path}.to`) }); } const exact = exactRecord(effect, ["type", "from", "to"], path); return Object.freeze({ type, from: text(exact.from, `${path}.from`), to: text(exact.to, `${path}.to`) }); }
function parseCursor(value: unknown, path: string): RawRuntimeCursor { const cursor = exactRecord(value, CURSOR_KEYS, path); return Object.freeze({ unit: text(cursor.unit, `${path}.unit`), unitInstance: nonnegativeInteger(cursor.unitInstance, `${path}.unitInstance`), localFrame: nonnegativeInteger(cursor.localFrame, `${path}.localFrame`) }); }
function parseOperation(value: unknown, index: number): RawRuntimeOperationEvent { const path = `$scenario.operations[${String(index)}]`; const operation = record(value, path); const kind = enumeration(operation.kind, ["input", "headed-dispatch", "promise", "dom-event"] as const, `${path}.kind`); const common = { eventOrdinal: nonnegativeInteger(operation.eventOrdinal, `${path}.eventOrdinal`), atMicroseconds: nonnegativeInteger(operation.atMicroseconds, `${path}.atMicroseconds`) }; if (kind === "input") { const exact = exactRecord(operation, ["eventOrdinal", "atMicroseconds", "kind", "operationOrdinal", "inputSequence", "target"], path); return Object.freeze({ ...common, kind, operationOrdinal: nonnegativeInteger(exact.operationOrdinal, `${path}.operationOrdinal`), inputSequence: nonnegativeInteger(exact.inputSequence, `${path}.inputSequence`), target: text(exact.target, `${path}.target`) }); } if (kind === "headed-dispatch") { const exact = exactRecord(operation, ["eventOrdinal", "atMicroseconds", "kind", "operationOrdinal", "eventType"], path); return Object.freeze({ ...common, kind, operationOrdinal: nonnegativeInteger(exact.operationOrdinal, `${path}.operationOrdinal`), eventType: enumeration(exact.eventType, ["pointerenter", "pointerleave", "focusin", "focusout", "click"] as const, `${path}.eventType`) }); } if (kind === "promise") { const exact = exactRecord(operation, ["eventOrdinal", "atMicroseconds", "kind", "operationOrdinal", "status", "errorName"], path); return Object.freeze({ ...common, kind, operationOrdinal: nonnegativeInteger(exact.operationOrdinal, `${path}.operationOrdinal`), status: enumeration(exact.status, ["fulfilled", "rejected"] as const, `${path}.status`), errorName: nullableText(exact.errorName, `${path}.errorName`) }); } const exact = exactRecord(operation, ["eventOrdinal", "atMicroseconds", "kind", "name", "from", "to", "edge", "sequence"], path); return Object.freeze({ ...common, kind, name: enumeration(exact.name, ["requestedstatechange", "transitionstart", "visualstatechange", "transitionend"] as const, `${path}.name`), from: text(exact.from, `${path}.from`), to: text(exact.to, `${path}.to`), edge: nullableText(exact.edge, `${path}.edge`), sequence: nullableInteger(exact.sequence, `${path}.sequence`) }); }
function parseResourceEvent(value: unknown, index: number): RawRuntimeResourceEvent { const path = `$scenario.resourceEvents[${String(index)}]`; const event = exactRecord(value, RESOURCE_KEYS, path); return Object.freeze({ eventOrdinal: nonnegativeInteger(event.eventOrdinal, `${path}.eventOrdinal`), atMicroseconds: nonnegativeInteger(event.atMicroseconds, `${path}.atMicroseconds`), kind: enumeration(event.kind, ["acquired", "retired"] as const, `${path}.kind`), resourceId: text(event.resourceId, `${path}.resourceId`), resourceBytes: positiveInteger(event.resourceBytes, `${path}.resourceBytes`), ownedResources: nonnegativeInteger(event.ownedResources, `${path}.ownedResources`), ownedBytes: nonnegativeInteger(event.ownedBytes, `${path}.ownedBytes`) }); }
function parseCleanupReceipt(value: unknown): RuntimeScenarioLedger["cleanupReceipt"] { const receipt = exactRecord(value, RECEIPT_KEYS, "$scenario.cleanupReceipt"); literal(receipt.reason, "dispose", "$scenario.cleanupReceipt.reason"); const retiredResourceIds = array(receipt.retiredResourceIds, "$scenario.cleanupReceipt.retiredResourceIds", 100_000).map((id, index) => text(id, `$scenario.cleanupReceipt.retiredResourceIds[${String(index)}]`)); return Object.freeze({ reason: "dispose", retiredResourceIds: Object.freeze(retiredResourceIds), ownedResources: nonnegativeInteger(receipt.ownedResources, "$scenario.cleanupReceipt.ownedResources"), ownedBytes: nonnegativeInteger(receipt.ownedBytes, "$scenario.cleanupReceipt.ownedBytes"), liveWorkers: nonnegativeInteger(receipt.liveWorkers, "$scenario.cleanupReceipt.liveWorkers"), openFrames: nonnegativeInteger(receipt.openFrames, "$scenario.cleanupReceipt.openFrames"), pendingLoads: nonnegativeInteger(receipt.pendingLoads, "$scenario.cleanupReceipt.pendingLoads"), activeLeases: nonnegativeInteger(receipt.activeLeases, "$scenario.cleanupReceipt.activeLeases"), stalePublications: nonnegativeInteger(receipt.stalePublications, "$scenario.cleanupReceipt.stalePublications") }); }
function parseTerminalTrace(value: unknown): RuntimeScenarioLedger["terminalTrace"] { const terminal = exactRecord(value, ["lastTraceIndex", "contentTickRecords", "cumulativeUnderflows"], "$scenario.terminalTrace"); return Object.freeze({ lastTraceIndex: nonnegativeInteger(terminal.lastTraceIndex, "$scenario.terminalTrace.lastTraceIndex"), contentTickRecords: nonnegativeInteger(terminal.contentTickRecords, "$scenario.terminalTrace.contentTickRecords"), cumulativeUnderflows: nonnegativeInteger(terminal.cumulativeUnderflows, "$scenario.terminalTrace.cumulativeUnderflows") }); }
function parseCounters(value: unknown, path: string): RuntimeCounterSnapshot { const input = exactRecord(value, COUNTER_KEYS, path); return Object.freeze(Object.fromEntries(COUNTER_KEYS.map((name) => [name, nonnegativeInteger(input[name], `${path}.${name}`)]))) as unknown as RuntimeCounterSnapshot; }
function array(value: unknown, path: string, maximum: number): readonly unknown[] { if (!Array.isArray(value) || value.length > maximum) throw new TypeError(`${path} must be an array of at most ${String(maximum)} items`); return value; }
function record(value: unknown, path: string): Record<string, unknown> { if (value === null || typeof value !== "object" || Array.isArray(value)) throw new TypeError(`${path} must be an object`); return value as Record<string, unknown>; }
function exactRecord(value: unknown, keys: readonly string[], path: string): Record<string, unknown> { const result = record(value, path); const allowed = new Set(keys); for (const key of Object.keys(result)) if (!allowed.has(key)) throw new TypeError(`${path}.${key} is unknown`); for (const key of keys) if (!(key in result)) throw new TypeError(`${path}.${key} is required`); return result; }
function digest(value: unknown, path: string): string { if (typeof value !== "string" || !SHA256_PATTERN.test(value)) throw new TypeError(`${path} is invalid`); return value; }
function text(value: unknown, path: string): string { if (typeof value !== "string" || value.length < 1 || value.length > 128 || !/^[A-Za-z0-9][A-Za-z0-9._:-]{0,127}$/u.test(value)) throw new TypeError(`${path} is invalid`); return value; }
function nullableText(value: unknown, path: string): string | null { return value === null ? null : text(value, path); }
function nonnegativeInteger(value: unknown, path: string): number { if (!Number.isSafeInteger(value) || (value as number) < 0) throw new RangeError(`${path} must be a nonnegative safe integer`); return value as number; }
function positiveInteger(value: unknown, path: string): number { const result = nonnegativeInteger(value, path); if (result === 0) throw new RangeError(`${path} must be positive`); return result; }
function boundedInteger(value: unknown, path: string, minimum: number, maximum: number): number { const result = nonnegativeInteger(value, path); if (result < minimum || result > maximum) throw new RangeError(`${path} must be ${String(minimum)}..${String(maximum)}`); return result; }
function nullableInteger(value: unknown, path: string): number | null { return value === null ? null : nonnegativeInteger(value, path); }
function boolean(value: unknown, path: string): boolean { if (typeof value !== "boolean") throw new TypeError(`${path} must be boolean`); return value; }
function nullableBoolean(value: unknown, path: string): boolean | null { return value === null ? null : boolean(value, path); }
function enumeration<const T extends readonly string[]>(value: unknown, values: T, path: string): T[number] { if (typeof value !== "string" || !values.includes(value)) throw new TypeError(`${path} is invalid`); return value as T[number]; }
function literal<const T extends string>(value: unknown, expected: T, path: string): asserts value is T { if (value !== expected) throw new TypeError(`${path} must be ${expected}`); }
